---
etcd_data_dir: /var/lib/etcd

etcd_kubeadm_enabled: false

bin_dir: /usr/local/bin
loadbalancer_apiserver_localhost: true
loadbalancer_apiserver_type: nginx 

loadbalancer_apiserver_port: 6443

loadbalancer_apiserver_healthcheck_port: 8081