---
kube_config_dir: /etc/kubernetes
kube_script_dir: "{{ bin_dir }}/kubernetes-scripts"
kube_manifest_dir: "{{ kube_config_dir }}/manifests"

kube_cert_dir: "{{ kube_config_dir }}/ssl"

kube_token_dir: "{{ kube_config_dir }}/tokens"

kube_users_dir: "{{ kube_config_dir }}/users"

kube_api_anonymous_auth: true

kube_version: v1.15.3

kube_image_repo: "gcr.io/google-containers"

local_release_dir: "/tmp/releases"
retry_stagger: 5

kube_cert_group: kube-cert

kube_log_level: 2

credentials_dir: "{{ inventory_dir }}/credentials"

kube_api_pwd: "{{ lookup('password', credentials_dir + '/kube_user.creds length=15 chars=ascii_letters,digits') }}"
kube_users:
  kube:
    pass: "{{kube_api_pwd}}"
    role: admin
    groups:
      - system:masters






kube_network_plugin: calico

kube_network_plugin_multus: false

kube_service_addresses: 10.233.0.0/18

kube_pods_subnet: 10.233.64.0/18

kube_network_node_prefix: 24

kube_apiserver_ip: "{{ kube_service_addresses|ipaddr('net')|ipaddr(1)|ipaddr('address') }}"

kube_proxy_mode: ipvs

kube_proxy_nodeport_addresses: >-
  {%- if kube_proxy_nodeport_addresses_cidr is defined -%}
  [{{ kube_proxy_nodeport_addresses_cidr }}]
  {%- else -%}
  []
  {%- endif -%}


kube_encrypt_secret_data: false

cluster_name: cluster.local
ndots: 2
dns_mode: coredns
enable_nodelocaldns: true
nodelocaldns_ip: 169.254.25.10
nodelocaldns_health_port: 9254
enable_coredns_k8s_external: false
coredns_k8s_external_zone: k8s_external.local
enable_coredns_k8s_endpoint_pod_names: false

resolvconf_mode: docker_dns
deploy_netchecker: false
skydns_server: "{{ kube_service_addresses|ipaddr('net')|ipaddr(3)|ipaddr('address') }}"
skydns_server_secondary: "{{ kube_service_addresses|ipaddr('net')|ipaddr(4)|ipaddr('address') }}"
dns_domain: "{{ cluster_name }}"

container_manager: docker

etcd_deployment_type: docker
kubelet_deployment_type: host
helm_deployment_type: host

kubeadm_control_plane: false
kubeadm_certificate_key: "{{ lookup('password', credentials_dir + '/kubeadm_certificate_key.creds length=64 chars=hexdigits') | lower }}"

k8s_image_pull_policy: IfNotPresent

kubernetes_audit: false

dynamic_kubelet_configuration: false

default_kubelet_config_dir: "{{ kube_config_dir }}/dynamic_kubelet_dir"
dynamic_kubelet_configuration_dir: "{{ kubelet_config_dir | default(default_kubelet_config_dir) }}"

podsecuritypolicy_enabled: false

kubeconfig_localhost: true







volume_cross_zone_attachment: false
persistent_volumes_enabled: false

